### ISSUE TITLE
[Request] Update `examples/jenkins-kubernetes-plugin-with-build-cache` with ephemeral volume usage

### ISSUE THREAD

**Issue by lucasvc** [plumber-cd/kubernetes-dynamic-reclaimable-pvc-controllers#19]
I came here from your comments on the https://issues.jenkins.io/browse/JENKINS-42422 issue.

I also read that [Provisioner Controller is deprecated](https://github.com/plumber-cd/kubernetes-dynamic-reclaimable-pvc-controllers/commit/1d92895494e4bbf2802fac5cc527ea6c7b149183) in favor of the [Ephemeral Volumes](https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/).

But I am recently entering the Jenkins using Kubernetes world, and I am struggling to understand more or less how everything is tied.

I have seen the example [jenkins-kubernetes-plugin-with-build-cache](https://github.com/plumber-cd/kubernetes-dynamic-reclaimable-pvc-controllers/tree/main/examples/jenkins-kubernetes-plugin-with-build-cache) which still make use of the provisioner. Could be possible to update that example (or create a new one) with the usage of the releaser along with the ephemeral volumes?

**Comment by dee-kryvenko** [comment]
Hey @lucasvc - thanks for the interest in this little project! I just removed all mentions of that deprecated provisioner from the docs, and updated all examples for native k8s `ephemeral` volumes. Check it out of it works and let me know if you find anything I missed! It is still there in the code though.
