### ISSUE TITLE
Add better jenkins examples

### ISSUE THREAD

**Issue by dee-kryvenko** [plumber-cd/kubernetes-dynamic-reclaimable-pvc-controllers#7]
As suggested by @jglick in https://github.com/plumber-cd/kubernetes-dynamic-reclaimable-pvc-controllers/pull/6 - need better real life examples with Jenkins.

**Comment by jglick** [comment]
Looks nice. Those samples are tested?

**Comment by dee-kryvenko** [comment]
Thanks. Yep I tested them.
