### ISSUE TITLE
Hello，does storageClass support nfs？

### ISSUE THREAD

**Issue by Johnnyliu007** [plumber-cd/kubernetes-dynamic-reclaimable-pvc-controllers#9]

**Comment by dee-kryvenko** [comment]
Hi @Johnnyliu007, this provisioner and reclaimer are agnostic of the backend CSI implementation - they just manipulate the state of a PV within kubernetes. It doesn't do anything with the storage itself. That said - I see no reason it should be having any issues with NFS but let me know if you find any issues.

**Comment by dee-kryvenko** [comment]
Assuming there was no issues - closing this ticket.
